version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@foo-software/lighthouse-check"
    versions:
    - "> 0.0.90"
  - dependency-name: "@octokit/rest"
    versions:
    - "> 16.43.1"
  - dependency-name: "@types/next-redux-wrapper"
    versions:
    - "> 2.0.2"
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.4
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.3.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: autocannon
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.5
  - dependency-name: danger
    versions:
    - 10.6.0
    - 10.6.1
    - 10.6.2
    - 10.6.3
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
