language: node_js
node_js:
  - '8'
cache: npm
script: npm run deploy
env:
  global:
    # NOW_TOKEN
    secure: e+ipBLOi+P+FbvP+MKP1mru/49EUh4MzdvjiSFYEU8Sr6Pr2+8QQICt6g0xQai3LIBqeeQjDP+qIjbyJNtQw8OugX9PcHEEXHeWj2XbJez1x4BSwbBJQ3b/ZfS0Q8Ivu9ir4gs8bC3MIATd4+nC7/DoS0cdr4TXtgiOhvktERT5kGBSTz4ooCcoOh3p8LCoaqyiLPHZEVEOjhTeDlBg5fAwY7IAIxQIypC7jQsdgnkUcIIXEiUF1EsctPuvXfQ3qQ8rU2Cn8PYZpVzwo5cxhiuXO0FLrbCghPewUYlQzIu3cDV1nM7tlN1yEaPAg5YWpWnZbTbSJltZbjMibtd6qBS7Sx1eeW9IY0LHP36ZBdudf6Ow0R3M8NcoDSG3gFVyzuHhAoehTeTvKKf2K0xIVdPu3CxuwSZ6wXAou4hN1EMf1qawyJQTyA/Z6X5EEpmqn89DXxtrxrH8Aig/6V1Woe5nv0DKRDQkSaNoGZJwZ07ZrS3kECuzWS31jgVqKBTwea7wsNDBm1P0tPrlLZGQ2wFg4deXsVMGdEQE4vx0Invon3Tpfn6zDkYl9/wZ/rMykFO9kJ9qFlVBaw9cFSuK2AYKcSG+UJ05EYlYptyoiQgGcSJ8YH7gvOtYs2CvJmszDx61O70bgNuBlmNvog34GQ5S4OPdU4gYEKadXuACOaHg=
