import { QueryInterface, SequelizeStatic } from 'sequelize';

// this is just for the initial migration, don't do it later on
// this SQL was generated by Sequelize
import * as fs from 'fs';
const rawSql = fs.readFileSync(__dirname + '/backup.sql', 'utf-8');

module.exports = {
  async up(queryInterface: QueryInterface, _Sequelize: SequelizeStatic) {
    await queryInterface.sequelize.query(rawSql, {});
  },

  async down(queryInterface: QueryInterface, _Sequelize: SequelizeStatic) {
    await queryInterface.dropAllTables();
    await queryInterface.dropAllEnums();
    await queryInterface.dropAllSchemas();
  },
};
