// tslint:disable:ordered-imports max-line-length variable-name
// THIS FILE IS GENERATED BY JOI-TS-GENERATOR. ANY CHANGES MADE WILL BE LOST.

export type QuestionCategoryJoi =
  | "html"
  | "css"
  | "js";

export type QuestionStatusJoi =
  | "accepted"
  | "pending"
  | "rejected";

export type GetQuestionsResponse = OneQuestionJoi[];

export interface OneQuestionJoi {
  id: number;
  question: string;
  category: QuestionCategoryJoi;
  level?: string;
  answer?: string;
  acceptedAt?: Date;
}

export interface GetQuestionsRequestQuery {
  category: QuestionCategoryJoi;
  status?: undefined;
}

// Unknown type: GetQuestionsRequest ([object Object])}
export interface CreateQuestionRequestPayload {
  question: string;
  level: string;
  category: QuestionCategoryJoi;
}

// Unknown type: CreateQuestionRequest ([object Object])}
export interface CreateQuestionResponse {
  id: number;
  question: string;
  category: QuestionCategoryJoi;
  level?: string;
  answer?: string;
  status: QuestionStatusJoi;
}

export interface CreateTokenRequestPayload {
  email: string;
  password: string;
}

// Unknown type: CreateTokenRequest ([object Object])}
export interface CreateTokenResponse {
  token: string;
}
