// tslint:disable:ordered-imports max-line-length variable-name
// THIS FILE IS GENERATED BY JOI-TS-GENERATOR. ANY CHANGES MADE WILL BE LOST.
import { QuestionCategories, QuestionCategory, QuestionLevel, QuestionStatus, QuestionStatuses } from "../entity/question/Question.model";

export type GetQuestionsResponse = OneQuestionJoi[];

export interface OneQuestionJoi {
  id: number;
  question: string;
  category: QuestionCategory;
  level?: string;
  answer?: string;
  acceptedAt?: Date;
}

export interface GetQuestionsRequestQuery {
  category: QuestionCategory;
  status?: QuestionStatuses;
  level?: QuestionLevel;
}

// Unknown type: GetQuestionsRequest ([object Object])}
export interface CreateQuestionRequestPayload {
  question: string;
  level: string;
  category: QuestionCategory;
}

// Unknown type: CreateQuestionRequest ([object Object])}
export interface CreateQuestionResponse {
  id: number;
  question: string;
  category: QuestionCategory;
  level?: string;
  answer?: string;
  status: QuestionStatus;
}

export interface CreateTokenRequestPayload {
  email: string;
  password: string;
}

// Unknown type: CreateTokenRequest ([object Object])}
export interface CreateTokenResponse {
  token: string;
}

export { QuestionCategories, QuestionCategory, QuestionLevel, QuestionStatus, QuestionStatuses };
