// tslint:disable:ordered-imports max-line-length variable-name
// THIS FILE IS GENERATED BY JOI-TS-GENERATOR. ANY CHANGES MADE WILL BE LOST.

import { coerceValue } from "./library";
import * as s from "../../allschemas";
import * as t from "./types";

export const CreateQuestionRequestUtils = {
  coerce: coerceValue<t.CreateQuestionRequest>(s.CreateQuestionRequestSchema),
};

export const CreateQuestionRequestPayloadUtils = {
  coerce: coerceValue<t.CreateQuestionRequestPayload>(s.CreateQuestionRequestPayloadSchema),
};

export const CreateQuestionResponseUtils = {
  coerce: coerceValue<t.CreateQuestionResponse>(s.CreateQuestionResponseSchema),
};

export const CreateTokenRequestUtils = {
  coerce: coerceValue<t.CreateTokenRequest>(s.CreateTokenRequestSchema),
};

export const CreateTokenRequestPayloadUtils = {
  coerce: coerceValue<t.CreateTokenRequestPayload>(s.CreateTokenRequestPayloadSchema),
};

export const CreateTokenResponseUtils = {
  coerce: coerceValue<t.CreateTokenResponse>(s.CreateTokenResponseSchema),
};

export const GetQuestionsRequestUtils = {
  coerce: coerceValue<t.GetQuestionsRequest>(s.GetQuestionsRequestSchema),
};

export const GetQuestionsRequestQueryUtils = {
  coerce: coerceValue<t.GetQuestionsRequestQuery>(s.GetQuestionsRequestQuerySchema),
};

export const GetQuestionsResponseUtils = {
  coerce: coerceValue<t.GetQuestionsResponse>(s.GetQuestionsResponseSchema),
};

export const OneQuestionJoiUtils = {
  coerce: coerceValue<t.OneQuestionJoi>(s.OneQuestionJoiSchema),
};

export const QuestionCategoryJoiUtils = {
  coerce: coerceValue<t.QuestionCategoryJoi>(s.QuestionCategoryJoiSchema),
};

export const QuestionStatusJoiUtils = {
  coerce: coerceValue<t.QuestionStatusJoi>(s.QuestionStatusJoiSchema),
};
